routes/web.php
<?php

Route::group(['middleware'  =>  ['auth']], function(){
    Route::get('home', 'HomeController@index')->name('index');
    Route::post('aluno/show', 'alunoController@searchAluno')->name('aluno.search');
    Route::post('professor/show', 'professorController@searchProfessor')->name('professor.search');
    Route::post('curso/show', 'cursoController@searchCurso')->name('curso.search');
    Route::post('turma/show', 'turmaController@searchTurma')->name('turma.search');
    Route::post('semestre/show', 'semestreController@searchSemestre')->name('semestre.search');
    Route::post('disciplina/show', 'disciplinaController@searchDisciplina')->name('disciplina.search');
    Route::post('matricula/show', 'matriculaController@searchMatricula')->name('matricula.search');
    Route::post('matdisciplina/show', 'matdisciplinaController@searchMatdisciplina')->name('matdisciplina.search');


});

Route::resource('/aluno', 'alunoController',[
    'names' => [
        'store' => 'aluno.store',
        'show'  =>  'aluno.show',
        'edit'  =>  'aluno.edit',
        'update' => 'aluno.update',
    ]
])->middleware('auth');

Route::resource('/professor', 'professorController',[
    'names' => [
        'store' => 'professor.store',
        'show'  =>  'professor.show',
        'edit'  =>  'professor.edit',
        'update' => 'professor.update',
    ]
])->middleware('auth');

Route::resource('/curso', 'cursoController',[
    'names' => [
        'store' => 'curso.store',
        'show'  =>  'curso.show',
        'edit'  =>  'curso.edit',
        'update' => 'curso.update',
    ]
])->middleware('auth');

Route::resource('/turma', 'turmaController',[
    'names' => [
        'store' => 'turma.store',
        'show'  =>  'turma.show',
        'edit'  =>  'turma.edit',
        'update' => 'turma.update',
    ]
])->middleware('auth');

Route::resource('/semestre', 'semestreController',[
    'names' => [
        'store' => 'semestre.store',
        'show'  =>  'semestre.show',
        'edit'  =>  'semestre.edit',
        'update' => 'semestre.update',
    ]
])->middleware('auth');

Route::resource('/disciplina', 'disciplinaController',[
    'names' => [
        'store' => 'disciplina.store',
        'show'  =>  'disciplina.show',
        'edit'  =>  'disciplina.edit',
        'update' => 'disciplina.update',
    ]
])->middleware('auth');

Route::resource('/matricula', 'matriculaController',[
    'names' => [
        'store' => 'matricula.store',
        'show'  =>  'matricula.show',
        'edit'  =>  'matricula.edit',
        'update' => 'matricula.update',
    ]
])->middleware('auth');

Route::resource('/matdisciplina', 'matdisciplinaController',[
    'names' => [
        'index' => 'matdisciplina.index',
        'store' => 'matdisciplina.store',
        'show'  =>  'matdisciplina.show',
        'edit'  =>  'matdisciplina.edit',
        'update' => 'matdisciplina.update',
        'destroy' => 'matdisciplina.destroy'
    ]
])->middleware('auth');

Route::resource('/nota', 'notaController',[
    'names' => [
        'index' => 'nota.index',
        'store' => 'nota.store',
        'show'  =>  'nota.show',
        'edit'  =>  'nota.edit',
        'update' => 'nota.update',
        'destroy' => 'nota.destroy',
    ]
])->middleware('auth');

Route::resource('/frequencia', 'frequenciaController',[
    'names' => [
        'index' => 'frequencia.index',
        'store' => 'frequencia.store',
        'show'  =>  'frequencia.show',
        'edit'  =>  'frequencia.edit',
        'update' => 'frequencia.update',
        'destroy' => 'frequencia.destroy',
    ]
])->middleware('auth');

Route::resource('/aula', 'aulaController',[
    'names' => [
        'index' => 'aula.index',
        'store' => 'aula.store',
        'show'  =>  'aula.show',
        'edit'  =>  'aula.edit',
        'update' => 'aula.update',
        'destroy' => 'aula.destroy',
    ]
])->middleware('auth');

Route::post('/atualizar-perfil', 'userController@profileUpdate')->name('profile.update')->middleware('auth');
Route::get('/meu-perfil', 'userController@profile')->name('profile')->middleware('auth');

Route::get('/alunodisciplina', 'matdisciplinaController@aludisCreate')->name('matdisciplina.aludiscreate')->middleware('auth');
Route::post('/alunodisciplina-create', 'matdisciplinaController@aludisStore')->name('matdisciplina.aludisstore')->middleware('auth');

Route::get('/json-disciplinas', 'disciplinaController@disciplinas');

Route::get('/semestreFrequencia', 'aulaController@semestreCreate')->name('frequencia.semestrecreate')->middleware('auth');

Route::get('/frequencia/{cddisciplina}/{cdsemestre}', 'aulaController@create', function ($cddisciplina, $cdsemestre){
    return view('cadastroFrequencia')->with('cddisciplina', $cddisciplina)->with('cdsemestre', $cdsemestre);
})->name('aulacreate.create');

Route::group(['middleware' => ['auth']], function(){
    Route::get('/sobre', function (){
        return view('sobre');
    });
});

Route::get('/', 'SiteController@index')->name('home');


Auth::routes();

resources/views/cadastroAluno.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Aluno')

@section('content_header')
@stop

@section('content')
<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Aluno</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>CADASTRO DOS DADOS DO ALUNO</b></h4>
      <br>              
    </div>
                
    <div class="box box-primary">
      
      <div class="box-body">
      @if ($errors->any())
        <div class="alert alert-warning">
          @foreach ($errors->all() as $error)
            <p>{{$error}}</p>
          @endforeach
        </div>
      @endif
        <form method="POST" action="{{ route('aluno.store')}}">
          @csrf
          <div class="row">
            <div class="col-md-2">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Número matricula:</font></font></label>
              <input type="text" name='nmatricula' class="form-control" placeholder="">
            </div>
            <div class="col-md-5">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nome completo:</font></font></label>
              <input type="text" name='nome' class="form-control" placeholder="">
            </div>
            <div class="col-md-3">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">CPF:</font></font></label>
              <input type="text" name='cpf' class="form-control" onkeypress="$(this).mask('000.000.000-00');" placeholder="">
            </div>
            <div class="col-md-2">
            <div class="form-group">
              <label for="inputStatus">Status:</label>
              <select name='status' class="form-control">
                <option selected>AT</option>
                <option>IN</option>
              </select>
            </div>
            </div> 
          </div>
                  
          <div class="box-footer" style="margin-top: 4%;">
            <a href="{{route('index')}}" class="btn btn-default">Cancelar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          </div>
                      
        </form>
      </div>
    </div>             
  </div>
</div>
<!-- /.box-body -->
          
            
@stop

resources/views/cadastroCurso.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Curso')

@section('content_header')
@stop

@section('content')
<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Curso</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>CADASTRO DOS DADOS DO CURSO</b></h4>
      <br>              
    </div>
                
    <div class="box box-primary">
      
      <div class="box-body">
      @if ($errors->any())
        <div class="alert alert-warning">
          @foreach ($errors->all() as $error)
            <p>{{$error}}</p>
          @endforeach
        </div>
      @endif
        <form method="POST" action="{{ route('curso.store')}}">
          @csrf
          <div class="row">
            <div class="col-md-6">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nome:</font></font></label>
              <input type="text" name='nomecurso' class="form-control" placeholder="">
            </div>
            <div class="col-md-3">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Valor:</font></font></label>
              <input type="text" name='valorcurso' class="form-control" placeholder="">
            </div>
          </div>
                  
          <div class="box-footer" style="margin-top: 4%;">
            <a href="{{route('index')}}" class="btn btn-default">Cancelar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          </div>
                      
        </form>
      </div>
    </div>             
  </div>
</div>
<!-- /.box-body -->
          
            
@stop

resources/views/cadastroDisciplina.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Disciplina')

@section('content_header')
@stop

@section('content')
<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Disciplina</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>CADASTRO DOS DADOS DA DISCIPLINA</b></h4>
      <br>              
    </div>
                
    <div class="box box-primary">
      
      <div class="box-body">
      @if ($errors->any())
        <div class="alert alert-warning">
          @foreach ($errors->all() as $error)
            <p>{{$error}}</p>
          @endforeach
        </div>
      @endif
        <form method="POST" action="{{ route('disciplina.store')}}">
          @csrf
          <div class="row">
            <div class="col-md-3">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nome:</font></font></label>
              <input type="text" name='nomedisciplina' class="form-control" placeholder="">
            </div>
            <div class="col-md-3">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Valor:</font></font></label>
              <input type="text" name='valor' class="form-control" placeholder="">
            </div>
            <div class="col-md-3">
            <div class="form-group">
              <label for="inputStatus">Professor:</label>
              <select name='cdprofessor' class="form-control">
              <option value="" disabled selected>Selecione o professor</option>
              @foreach ($disciplinas_prof as $value)
                <option value={{$value->cdprofessor}}>{{$value->nome}} - {{$value->nciape}}</option>
              @endforeach
              </select>
            </div>
            </div> 
            <div class="col-md-3">
            <div class="form-group">
              <label for="inputStatus">Curso:</label>
              <select name='cdcurso' class="form-control">
              <option value="" disabled selected>Selecione o curso</option>
              @foreach ($disciplinas_curso as $value)
                <option value={{$value->cdcurso}}>{{$value->nomecurso}}</option>
              @endforeach
              </select>
            </div>
            </div> 
          </div>
                  
          <div class="box-footer" style="margin-top: 4%;">
            <a href="{{route('index')}}" class="btn btn-default">Cancelar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          </div>
                      
        </form>
      </div>
    </div>             
  </div>
</div>
<!-- /.box-body -->
          
            
@stop

resources/views/cadastroMatricula.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Matricula')

@section('content_header')
@stop

@section('content')
<link rel="stylesheet" href="{{ asset('public/css/css.css') }}">

<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Matricula</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>CADASTRO DOS DADOS DA MATRICULA</b></h4>
      <br>              
    </div>
                
    <div class="box box-primary">
      
      <div class="box-body">
      @if ($errors->any())
        <div class="alert alert-warning">
          @foreach ($errors->all() as $error)
            <p>{{$error}}</p>
          @endforeach
        </div>
      @endif
      <h5><b>Selecione os dados de matricula do aluno:</b></h5>
      <br>
        <form method="POST" action="{{ route('matricula.store')}}">
          @csrf
          <div class="row">
            <div class="col-md-4">
            <div class="form-group">
              <label for="inputAluno">Aluno:</label>
              <select name='cdaluno' class="form-control">
              <option value="" disabled selected>Selecione o aluno</option>
              @foreach ($data['aluno'] as $value)
                <option value={{$value->cdaluno}}>{{$value->nome}} - {{$value->nmatricula}}</option>
              @endforeach
              </select>
            </div>
            </div> 
            <div class="col-md-4">
            <div class="form-group">
              <label for="inputCurso">Curso:</label>
              <select name='cdcurso' id='cdcurso' class="form-control">
              <option value="" disabled selected>Selecione o curso</option>
              @foreach ($data['curso'] as $value)
                <option value="{{$value->cdcurso}}">{{$value->nomecurso}}</option>
              @endforeach
              </select>
            </div>
            </div>
            <div class="col-md-4">
            <div class="form-group">
              <label for="inputSemestre">Semestre:</label>
              <select name='cdsemestre' class="form-control">
              <option value="" disabled selected>Selecione o semestre</option>
              @foreach ($data['semestre'] as $value)
                <option value={{$value->cdsemestre}}>{{$value->ano}}</option>
              @endforeach
              </select>
            </div>
            </div>
            <div class="col-md-4">
            <div class="form-group">
              <label for="inputTurma">Turma:</label>
              <select name='cdturma' class="form-control">
              <option value="" disabled selected>Selecione a turma</option>
              @foreach ($data['turma'] as $value)
                <option value={{$value->cdturma}}>{{$value->nometurma}}</option>
              @endforeach
              </select>
            </div>
            </div>
            <div class="col-md-4">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Valor:</font></font></label>
              <input type="text" name='valor' class="form-control" placeholder="Valor do curso">
            </div>
            <div class="col-md-4">
            <div class="form-group">
              <label for="inputStatus">Status:</label>
              <select name='statusMat' class="form-control">
                <option selected>AT</option>
                <option>IN</option>
              </select>
            </div>
            </div>
            
            <div class="col-md-4">
            <h5 class="ml-3"><b>Selecione as disciplinas do aluno:</b></h5>
            <br>
            <div class="form-group">
              <label for="inputStatus">Disciplinas:</label>
              <select style="color: #000000 !important;" name='cddisciplina[]' id='cddisciplina' class="form-control" multiple="multiple">
              </select>
            </div>
            </div>
          </div>
                  
          <div class="box-footer" style="margin-top: 4%;">
            <a href="{{route('index')}}" class="btn btn-default">Cancelar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          </div>
                      
        </form>
      </div>
    </div>             
  </div>
</div>
<!-- /.box-body -->
          
            
@stop

resources/views/cadastroNota.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Nota')

@section('content_header')
@stop

@section('content')
<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Nota</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>CADASTRO DOS DADOS DA NOTA</b></h4>
      <br>              
    </div>
                
    <div class="box box-primary">
      
      <div class="box-body">
      @if ($errors->any())
        <div class="alert alert-warning">
          @foreach ($errors->all() as $error)
            <p>{{$error}}</p>
          @endforeach
        </div>
      @endif
        <form method="POST" action="{{ route('nota.store')}}">
          @csrf
          <div class="row">
              <input type="hidden" name='cdmatdisciplina' value="{{$cdmat}}">
            
            <div class="col-md-2">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nota:</font></font></label>
              <input type="text" name='nota' class="form-control" placeholder="Nota">
            </div>
            <div class="col-md-4">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Referência:</font></font></label>
              <input type="text" name='referencia' class="form-control" placeholder="Referencia">
            </div>
            
          </div>
                  
          <div class="box-footer" style="margin-top: 4%;">
            <a href="{{route('matdisciplina.index')}}" class="btn btn-default">Cancelar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          </div>
                      
        </form>
      </div>
    </div>             
  </div>
</div>
<!-- /.box-body -->
          
            
@stop

resources/views/cadastroTurma.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Turma')

@section('content_header')
@stop

@section('content')
<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Turma</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>CADASTRO DOS DADOS DA TURMA</b></h4>
      <br>              
    </div>
                
    <div class="box box-primary">
      
      <div class="box-body">
      @if ($errors->any())
        <div class="alert alert-warning">
          @foreach ($errors->all() as $error)
            <p>{{$error}}</p>
          @endforeach
        </div>
      @endif
        <form method="POST" action="{{ route('turma.store')}}">
          @csrf
          <div class="row">
            <div class="col-md-5">
              <label><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nome:</font></font></label>
              <input type="text" name='nometurma' class="form-control" placeholder="">
            </div> 
          </div>
                  
          <div class="box-footer" style="margin-top: 4%;">
            <a href="{{route('index')}}" class="btn btn-default">Cancelar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          </div>
                      
        </form>
      </div>
    </div>             
  </div>
</div>
<!-- /.box-body -->
          
            
@stop

resources/views/form.blade.php
<div class="form-group">
	<label for="nmatricula">Número Matricula</label>
  @if(isset($aluno) && !empty($aluno->nmatricula)) 
  	<input type="text" class="form-control" name="nmatricula" id="nmatricula" value="{{ $aluno->nmatricula }}">
  @else
  	<input type="text" class="form-control" name="nmatricula" id="nmatricula">
  @endif
</div>

<div class="form-group">
	<label for="des">Nome</label>
  @if(isset($aluno) && !empty($aluno->nome))      
    <input type="text" class="form-control" name="nome" id="title" value="{{ $aluno->nome }}">
  @else
    <input type="text" class="form-control" name="nome" id="title">
  @endif
</div>

<div class="form-group">
  <label for="status">Status:</label>
  <select name='status' class="form-control">
    <option {{ isset($aluno) && !empty($aluno->status) && $aluno->status == 'AT' ? 'selected': '' }}>AT</option>
    <option {{ isset($aluno) && !empty($aluno->status) && $aluno->status == 'IN' ? 'selected': '' }}>IN</option>
  </select>
</div>

resources/views/listarCurso.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Curso')

@section('content_header')
@stop

@section('content')

<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Curso</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Consultar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>LISTA DOS CURSOS CADASTRADOS</b></h4>
      <br>              
    </div>

  
          <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font></font></h3>
              <a href="{{route('curso.create')}}" class="btn btn-primary"><i class="fas fa-plus"></i> Cadastrar</a>     
              </button>
              <form action="{{route('curso.search')}}" method="POST" class="form form-inline pull-right">
                {!! csrf_field() !!}
                <input type="text" name="nomecurso" class="form-control" placeholder="Nome Curso">

                <button type="submit" class="btn btn-default">Pesquisar</button>
              </form>

            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <thead>
                    <tr>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit; position: center;">Nome</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Valor</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ação</font></font></th>

                    </tr>
                </thead>
                <tbody>
                @foreach($listCurso as $value)
                    <tr>
                        <th>{{$value->nomecurso}}</th>
                        <th>{{$value->valorcurso}}</th>
                        <!-- <th><button type="button" class="edit-model btn btn-primary" data-mynmatricula="{{$value->nmatricula}}" data-mynome="{{$value->nome}}" data-mystatus="{{$value->status}}" data-valid="{{$value->cdaluno}}" data-toggle="modal" data-target="#edit"><i class="fas fa-user-edit"></i></button> -->
                        <th><a href="{{route('curso.edit', $value->cdcurso)}}" class="btn btn-warning"><i class="fas fa-pencil-alt"></i></a>
                        </th>
                    </tr>
                @endforeach
                
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

    @stop

resources/views/listarDisciplina.blade.php
@extends('adminlte::page')

@section('title', 'SIESCOLA - Disciplina')

@section('content_header')
@stop

@section('content')

<div id="line-one">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="center" style='text-align: center;'>              
        <h1><b>Disciplinas</b></h1>
        <br>
      </div>             
    </div>
            
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('index')}}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Consultar</li>
      </ol>
    </nav>              

                    
    <div class="row">  
      <br>
      <h4 id="center" style='text-align: center;'><b>LISTA DAS DISCIPLINAS CADASTRADAS</b></h4>
      <br>              
    </div>

  
          <div class="box box-primary">
            <div class="box-header">
            @include('messages')
              <h3 class="box-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font></font></h3>
              <a href="{{route('disciplina.create')}}" class="btn btn-primary"><i class="fas fa-plus"></i> Cadastrar</a>     
              </button>
              <form action="{{route('disciplina.search')}}" method="POST" class="form form-inline pull-right">
                {!! csrf_field() !!}
                <input type="text" name="nomedisciplina" class="form-control" placeholder="Nome Disciplina">
                <input type="text" name="nome" class="form-control" placeholder="Nome Professor">
                <button type="submit" class="btn btn-default">Pesquisar</button>
              </form>

            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <thead>
                    <tr>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit; position: center;">Nome</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Valor</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Professor</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Curso</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Editar</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Adicionar Frequência</font></font></th>
                        <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Aulas Cadastradas</font></font></th>

                    </tr>
                </thead>
                <tbody>
                @foreach($listDisciplina as $value)
                    <tr>
                        <th>{{$value->nomedisciplina}}</th>
                        <th>{{$value->valor}}</th>
                        <th>{{$value->professor($value->cdprofessor)->nome}}</th>
                        <th>{{$value->curso($value->cdcurso)->nomecurso}}</th>

                        <!-- <th><button type="button" class="edit-model btn btn-primary" data-mynmatricula="{{$value->nmatricula}}" data-mynome="{{$value->nome}}" data-mystatus="{{$value->status}}" data-valid="{{$value->cdaluno}}" data-toggle="modal" data-target="#edit"><i class="fas fa-user-edit"></i></button> -->
                        <th>
                          <a href="{{route('disciplina.edit', $value->cddisciplina)}}" class="btn btn-warning"><i class="fas fa-pencil-alt"></i></a>
                        </th>
                        <th>
                        <a href="{{route('frequencia.semestrecreate', ['cddisciplina' => $value->cddisciplina])}}" class="btn btn-primary"><i class="fas fa-list-alt"></i></a> 
                          <!-- <a href="{{route('aula.create', ['cddisciplina' => $value->cddisciplina])}}" class="btn btn-primary"><i class="fas fa-list-alt"></i></a> -->
                        </th>
                        <th>
                          <a href="{{route('aula.index', ['cddisciplina' => $value->cddisciplina])}}" class="btn btn-primary"><i class="fas fa-eye"></i></a>
                        </th>
                        
                    </tr>
                @endforeach
                
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

    @stop

resources/views/messages.blade.php
@if (session('success'))
    <div class = "alert alert-success">
        {{session('success')}}
    </div>
@endif

@if (session('errorDelete'))
    <div class = "alert alert-danger">
        {{session('errorDelete')}}
    </div>
@endif